### ISSUE TITLE
[Feature request] Ability to process 'Color.FromArgb'

### ISSUE THREAD

**Issue by Ordisoftware** [mrlacey/CSInlineColorViz#1]
Sample:

![image](https://user-images.githubusercontent.com/22332878/151649176-567a5d40-e155-4626-8ca9-5424bb7c97ac.png)

Also `FromKnownColor` and `FromName`.

**Comment by mrlacey** [comment]
Thanks for suggesting this.
I always thought it was a natural extension in functionality but was waiting to see if others thought this would be useful too. 😄

**Comment by mrlacey** [comment]
I should probably handle `System.Windows.Media.Color.FromRgb` too 😉

**Comment by Ordisoftware** [comment]
Indeed!

**Comment by mrlacey** [comment]
After a bit of faffing with regular expressions, I'm going to release a new version that can now handle the following.

If in the `System.Drawing` world:

![image](https://user-images.githubusercontent.com/189547/151661997-1c96043d-a91b-44fe-a8cd-82f566e8e49e.png)

Or if `System.Windows.Media` is more your thing:

![image](https://user-images.githubusercontent.com/189547/151662022-2df9c1c9-6b4f-4f82-8525-4eba5c61f0c7.png)


This doesn't handle every overload of the above methods or even all the available methods, but it's the easy ones. 😉

**Comment by mrlacey** [comment]
v1.2 should be available from the marketplace shortly.

**Comment by Ordisoftware** [comment]
It works great, thanks!

**Comment by mrlacey** [comment]
If you have any other problems, comments, or suggestions please raise another issue.
If you love it, please [leave a rating/review](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.CSInlineColorViz&ssr=false#review-details) or consider [sponsorship](https://github.com/sponsors/mrlacey)  :smile:
