### ISSUE TITLE
Doesn't work with Color32 and other examples

### ISSUE THREAD

**Issue by bgs801** [mrlacey/CSInlineColorViz#15]
New Color32(byte r,byte g,byte b,byte a)
New Color(float r, float g, float b, float a)  new Color(0f,1f,1f,0.15f) used in Unity
UnityEngine.Color(float r, float g, float b, float a)

**Comment by mrlacey** [comment]
Making progress here

![image](https://github.com/mrlacey/CSInlineColorViz/assets/189547/d6b04ed8-c572-4515-9261-0942a1b5b955)


New version coming soon

**Comment by mrlacey** [comment]
this is all included in v1.15
