### ISSUE TITLE
Color does not change automatically

### ISSUE THREAD

**Issue by vlasto77** [mrlacey/CSInlineColorViz#18]
Hi,

when I use Color.FromArgb("#ff7b68ee") it shows correct color for the first time. However, when I change the color string, color does not change automatically. I had to close and reopen file for changes to take effect. Could this be fixed, please?

**Comment by mrlacey** [comment]
Hi @vlasto77, I'm unable to recreate the issue you describe.
The screen clip below shows the color changing as I type to change the text.

![colorviz-issue18](https://github.com/user-attachments/assets/3bc63a36-77d7-4f4b-b067-b0aaec3a1e4f)


Some questions to help track down why you're seeing what you're reporting.

- Has this ever worked for you? (I released an update last week and wonder if this is part of the issue. If you're only using this for the first time, then that's irrelevant.)
- Which version of the extension do you have?
- Which version of Visual Studio are you using?
- What other extensions do you have installed?

**Comment by mrlacey** [comment]
It looks like this is a VS bug in the latest preview version. 
Please upvote https://developercommunity.visualstudio.com/t/ITaggerGetTags-in-the-VSSDK-appears-t/10798945

If you find the issue in older versions of VS please share that too.

**Comment by vlasto77** [comment]
I'm using it for the first time. And I do not use preview version of Visual Studio.
I use Visual Studio 17.12.1
Extension version: 1.15.1
I use more extensions but only one that affect code editor is [Viasfora](https://marketplace.visualstudio.com/items?itemName=TomasRestrepo.Viasfora) and I'm not sure about [CodeMaid](https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaidVS2022)

**Comment by mrlacey** [comment]
Reproducing this was tricky as "other things" happening in the background (including VS loading things) can make this difficult/inconsistent to recreate.
I think I have a fix though.

**Comment by mrlacey** [comment]
v1.17 (now in the marketplace) _should_ fix this.
