### ISSUE TITLE
ConsoleColor.DarkYellow doesn't show up

### ISSUE THREAD

**Issue by ItsaGlitch1** [mrlacey/CSInlineColorViz#4]
Was checking this tool out, and found that Dark Yellow doesn't show up when called.

![ConsoleColors](https://user-images.githubusercontent.com/23035675/194083728-96aa21ad-3e26-4b7b-b34a-34df848afc6b.png)

**Comment by mrlacey** [comment]
Thanks for reporting.
I used all the names colors from `System.Drawing.Coror` (+ a few other names common on the web) and never considered that ConsoleColor might contain other named values.
I'll add this now.

**Comment by mrlacey** [comment]
![image](https://user-images.githubusercontent.com/189547/194289246-afbdd50c-14ff-4aa0-8adb-5eca3dac82b6.png)

Now supported in version 1.7 (just released)
