### ISSUE TITLE
Support hex literals

### ISSUE THREAD

**Issue by SaalBC** [mrlacey/CSInlineColorViz#5]
Example: 
var color = 0xff0000;

I think it would be best to check if its exactly in this format since it could be mixed up with other hex literals that aren't colors like: 0x32ff

**Comment by SaalBC** [comment]
In the projects I'm working on I got it all the time, but I don't know how it's done in the majority of projects. I understand your concerns.
Maybe adding a setting to toggle it would be a thought.

**Comment by mrlacey** [comment]
Adding this.
Can make it configurable in the future if requested/needed.

![image](https://user-images.githubusercontent.com/189547/199745018-adfb835f-b5e6-4316-b230-453a437ab8ea.png)

Just published this functionality to the store as version 1.8.

If this is helpful, [ratings](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.CSInlineColorViz&ssr=false#review-details) and [sponsorship](https://github.com/sponsors/mrlacey) help :)
