### ISSUE TITLE
Add support for another Color From overloads

### ISSUE THREAD

**Issue by Diesel1017** [mrlacey/CSInlineColorViz#9]
_First thanks for the great extension, it helps a lot in my work!_

I found some overloads that are (i think)  not handled properly.
Sample (attached the image):

```
//Works
Color color = Color.FromArgb(40, 255, 255, 155);

//Not works
Color color1 = Color.FromKnownColor(KnownColor.ControlDark); //It would be great if you could support this format
Color color2 = Color.FromName("Red"); //This is not so necessary, but it may be worth thinking about

//Not working properly
Color color3 = Color.FromArgb(10, Color.Red);
Color color4 = Color.FromArgb(40, Color.Red);
```
![ColorFromOverloads](https://user-images.githubusercontent.com/2014473/220874772-b3167779-ce86-4b03-b119-884ccd4a7074.jpg)

Could these overrides be included at some point?

**Comment by mrlacey** [comment]
Nice suggestions

**Comment by mrlacey** [comment]
Support coming soon

teaser:
![image](https://github.com/mrlacey/CSInlineColorViz/assets/189547/bb101c73-5d42-4249-b36f-e9aa8b1c1dcb)

**Comment by mrlacey** [comment]
And all the above works without full namespace qualification too.

![image](https://github.com/mrlacey/CSInlineColorViz/assets/189547/e1ebf979-2fc8-4149-9d96-e70d5fae8710)

**Comment by Diesel1017** [comment]
Thank you, I will test it.
